out1 <- toyModel(model="dNMF")
out2 <- toyModel(model="dSVD")
out3 <- toyModel(model="dNTF")
out4 <- toyModel(model="dNTD")
out5 <- toyModel(model="dsiNMF_Easy")
out6 <- toyModel(model="dsiNMF_Hard")
out7 <- toyModel(model="PLS_Easy")
out8 <- toyModel(model="PLS_Hard")

expect_equivalent(length(dim(out1)), 2)
expect_equivalent(length(dim(out2)), 2)
expect_equivalent(length(dim(out3)), 3)
expect_equivalent(length(dim(out4)), 3)

expect_equivalent(length(out5), 3)
expect_equivalent(length(dim(out5[[1]])), 2)
expect_equivalent(length(dim(out5[[2]])), 2)
expect_equivalent(length(dim(out5[[3]])), 2)

expect_equivalent(length(out6), 3)
expect_equivalent(length(dim(out6[[1]])), 2)
expect_equivalent(length(dim(out6[[2]])), 2)
expect_equivalent(length(dim(out6[[3]])), 2)

expect_equivalent(length(out7), 3)
expect_equivalent(length(dim(out7[[1]])), 2)
expect_equivalent(length(dim(out7[[2]])), 2)
expect_equivalent(length(dim(out7[[3]])), 2)

expect_equivalent(length(out8), 3)
expect_equivalent(length(dim(out8[[1]])), 2)
expect_equivalent(length(dim(out8[[2]])), 2)
expect_equivalent(length(dim(out8[[3]])), 2)
