out1 <- toyModel(model="NMF")
out2 <- toyModel(model="CP")
out3 <- toyModel(model="Tucker")
out4 <- toyModel(model="siNMF_Easy")
out5 <- toyModel(model="siNMF_Hard")

expect_equivalent(length(dim(out1)), 2)
expect_equivalent(length(dim(out2)), 3)
expect_equivalent(length(dim(out3)), 3)
expect_equivalent(length(out4), 3)
expect_equivalent(length(dim(out4[[1]])), 2)
expect_equivalent(length(dim(out4[[2]])), 2)
expect_equivalent(length(dim(out4[[3]])), 2)
expect_equivalent(length(out5), 3)
expect_equivalent(length(dim(out5[[1]])), 2)
expect_equivalent(length(dim(out5[[2]])), 2)
expect_equivalent(length(dim(out5[[3]])), 2)
